config/routes.rb
SocialVacation::Application.routes.draw do
  resources :trips do 

  end
  match "/trips/find/images" => "trips#images" , :as => "find_images"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :trip
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  include Media
  has_many :activities, :dependent => :destroy
  attr_accessible :main_img, :name, :primary_url
  



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index

  end

  def new
    @trip = Trip.new
    render :layout => false
  end

  def create 
    @trip = Trip.new(params[:trip])
    respond_to do |format|
      if @trip.save 
        format.js
      end
    end
  end 

  def images
    @trip = Trip.new
    if params[:url]
      @images = @trip.scrape_images(params[:url])
    end
  end

  def new 
    @trip = Trip.new(:primary_url => params[:url])
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Bootstrap 101 Template
    = stylesheet_link_tag    "application", :media => "all" 
    
    = csrf_meta_tags 
  %body
    = yield
    = javascript_include_tag "application" 

app/views/shared/_nav.html.haml
.navbar.navbar-inverse
  .navbar-inner
    %ul.nav
      %li.active
        %a{:href => "#"} Home
      %li
        %a{:href => "#"} Link
      %li
        %a{:href => "/trips/new",  :"data-toggle" => "modal", :"data-target" => "#newtrip"} Create Trip

#newtrip.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel Create a new trip
  .modal-body
  .modal-footer
    %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Close
    %button.btn.btn-primary.create_trip Create New Trip

app/views/trips/_form.html.haml
=form_for @trip , :remote => true  do |f|
  =f.label :primary_url
  =f.text_field :primary_url
  =f.label :name
  =f.text_field :name

app/views/trips/_nav.html.haml
%ul.nav.nav-tabs
  %li.active
    %a{:href => "#"} Most Popular
  %li
    %a{:href => "#"} Least Popular
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      Dropdown
      %b.caret
    %ul.dropdown-menu
      
  %li.new_activity
    %a{:href => "#"} New Activity

app/views/trips/images.html.haml
.container
  =render "shared/nav"
  =form_tag find_images_path, :method => :get do 
    =text_field_tag :url

#main_wrap.container
  .row
    .span12
      %ul.thumbnails
        -if @images 
          -@images.each do |image|
            %li.span3
              =link_to( image_tag(image), new_trip_path(:url => image), :remote => true, :class => "thumbnail")

app/views/trips/index.html.haml
.container
  =render "shared/nav"
#main_wrap.container

  .row
    .span12.hero
      %img{:src => "/assets/haiti.jpg"}
      .info
        %h2 Cruise to haiti, jamaica, and mexico
        %p

          On the north coast of Haiti, surrounded by beautiful mountain slopes and exotic foliage, sits Labadee®, Royal Caribbean's private paradise. This exclusive destination offers pristine beaches, breathtaking scenery and spectacular water activities. We even have an amazing new Aqua Park for kids. Regardless of where you go, you'll find yourself embraced by the beautiful landscape. Labadee's native charm, along with its natural beauty, make this a destination not to be missed, and only Royal Caribbean can take you there.

  .row
    .span8
      .leftCol
        %h2 Activities
        =render "trips/nav"
        .media
          %a.pull-left{:href => "#"}
            %img.media-object{:src => "http://dummyimage.com/64x64/000/fff"}/
          .media-body
            %h4.media-heading Media heading
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            %h6 Price: $30.00
          .vote
            Visit Website: 
            %a{:href => "#"} http://www.royalcarribena.com
            %ul
              %li
                %span.icon-thumbs-up
                %a{:href => "#"} 0 Votes Yes
              %li
                %span.icon-thumbs-down
                %a{:href => "#"} 0 Votes No


        .media
          %a.pull-left{:href => "#"}
            %img.media-object{:src => "http://dummyimage.com/64x64/000/fff"}/
          .media-body
            %h4.media-heading Media heading
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          .vote
            %ul
              %li
                %span.icon-thumbs-up
                %a{:href => "#"} 0 Votes Yes
              %li
                %span.icon-thumbs-down
                %a{:href => "#"} 0 Votes No
      
    .span4
      %ul.nav.nav-list.sub_nav
        %li.nav-header List header
        %li.active
          %a{:href => "#"} Home
        %li
          %a{:href => "#"} Library